apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myredis
  name: redis
spec:
  ports:
  - port: 12000
    protocol: TCP
    targetPort: 12000
  selector:
    app: myredis
  type: ClusterIP
status:
  loadBalancer: {}
