apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb
  labels:
    type: local
spec:
  storageClassName: ssd
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/run/desktop/mnt/host/e/pv_mongodb'
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ssd
  volumeName: pv-mongodb
